### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by grumpykiwi** [thebookisclosed/AmperageKit#5] opened 2024-06-02 16:00 UTC
Is it possible to run the ARM Windows 11 ISO on an M3 MacBook Pro with Virtual BOX or VMWare Fusion?

Want to stay ahead of this monstrosity before it is enabled for the Intel/AMD devices in my domain. I will be shutting it down as soon as I can get my hands on the ADMX or it appears in Intune. Whichever happens first.

I realize this is probably a dumb question, but figured there might be other dummies out there thinking the same thing :-)

Thanks

Mark

**Comment by thebookisclosed** [comment] 2024-06-02 19:56
You can definitely do it with Fusion, just make sure to download the older version of this tool as per the Release's description.

**Comment by grumpykiwi** [comment] 2024-06-03 04:11
Thanks for the quick response.


Mark Nash

IT Director

(817) 465-9277  |  Arlington, Tx

Winner of 104 IABC Gold Quills and the 2023 Large Agency of the Year

[cid:linkedin_4c6f3bdf-dd4e-4f46-94f0-1885fa83094c.png]<https://www.linkedin.com/company/partnercomm>    [cid:instagram_bebedbe2-cb80-462a-af3c-7ae9caf0718c.png] <https://www.instagram.com/partnercomm>     [cid:facebook_a2d99c62-cb5a-42d3-b0e4-d08e71427149.png] <https://www.facebook.com/PartnerCommInc/>     [cid:twitter_53725725-ce5d-4ef3-bd47-bfd64fe511d7.png] <https://twitter.com/partnercomm>     [cid:vimeo_f71007e4-e318-469a-b82c-5751fc4fbe28.png] <https://vimeo.com/sweet250>                  [cid:web_a51bd891-a842-461a-b706-81937a9daae4.png]  www.partnercomm.net<https://www.partnercomm.net>
        [cid:logo-pcomm-30_74bce84a-c4e7-4724-87ee-9c2ca3e3421e.png]

________________________________

**Comment by grumpykiwi** [comment] 2024-06-03 19:29
Got it all installed and ran all the scripts. For some reason, Recall was not enabled by default. If I toggle it to on in Settings, the Settings app crashes and does not enable Recall.

Is there a way to enable via regedit perhaps ?



Mark Nash

IT Director

(817) 465-9277  |  Arlington, Tx

Winner of 104 IABC Gold Quills and the 2023 Large Agency of the Year

[cid:linkedin_4c6f3bdf-dd4e-4f46-94f0-1885fa83094c.png]<https://www.linkedin.com/company/partnercomm>    [cid:instagram_bebedbe2-cb80-462a-af3c-7ae9caf0718c.png] <https://www.instagram.com/partnercomm>     [cid:facebook_a2d99c62-cb5a-42d3-b0e4-d08e71427149.png] <https://www.facebook.com/PartnerCommInc/>     [cid:twitter_53725725-ce5d-4ef3-bd47-bfd64fe511d7.png] <https://twitter.com/partnercomm>     [cid:vimeo_f71007e4-e318-469a-b82c-5751fc4fbe28.png] <https://vimeo.com/sweet250>                  [cid:web_a51bd891-a842-461a-b706-81937a9daae4.png]  www.partnercomm.net<https://www.partnercomm.net>
        [cid:logo-pcomm-30_74bce84a-c4e7-4724-87ee-9c2ca3e3421e.png]

**Comment by thebookisclosed** [comment] 2024-06-03 19:39
Mind sending a screenshot of the Amperage ZIP you've downloaded? Also, what "scripts" did you run? There are no scripts to use

**Comment by grumpykiwi** [comment] 2024-06-03 20:42
Here you go. Thanks



Mark Nash

IT Director

(817) 465-9277  |  Arlington, Tx

Winner of 104 IABC Gold Quills and the 2023 Large Agency of the Year

[cid:linkedin_4c6f3bdf-dd4e-4f46-94f0-1885fa83094c.png]<https://www.linkedin.com/company/partnercomm>    [cid:instagram_bebedbe2-cb80-462a-af3c-7ae9caf0718c.png] <https://www.instagram.com/partnercomm>     [cid:facebook_a2d99c62-cb5a-42d3-b0e4-d08e71427149.png] <https://www.facebook.com/PartnerCommInc/>     [cid:twitter_53725725-ce5d-4ef3-bd47-bfd64fe511d7.png] <https://twitter.com/partnercomm>     [cid:vimeo_f71007e4-e318-469a-b82c-5751fc4fbe28.png] <https://vimeo.com/sweet250>                  [cid:web_a51bd891-a842-461a-b706-81937a9daae4.png]  www.partnercomm.net<https://www.partnercomm.net>
        [cid:logo-pcomm-30_74bce84a-c4e7-4724-87ee-9c2ca3e3421e.png]

**Comment by zorrobyte** [comment] 2024-06-05 11:17
I'll be testing this with Parallels (Windows Arm on Mac) shortly and will report my findings. It should be interesting as Windows on Apple Silicon is a pretty fast and good experience - would be hilarious if it was ultimately faster on Apple hardware

**Comment by hazcod** [comment] 2024-06-05 20:46
Trying with Windows 11 ARM on Parallels and tool version 2024.5.31 , but getting following error:
![image](https://github.com/thebookisclosed/AmperageKit/assets/5222512/019d187b-3a39-49c2-8f56-0b9b449a8580)

**Comment by Satertek** [comment] 2024-06-06 03:21
Looks like its working on my M3 Pro Macbook. 👍 

OS: Windows 11 (Pro) aarch64
Host: Parallels ARM Virtual Machine (0.1)
Kernel: WIN32_NT 10.0.26120.751 (24H2)

OS: macOS Sonoma 14.4.1 arm64
Host: MacBook Pro (14-inch, Nov 2023, Three Thunderbolt 4 ports)
Kernel: Darwin 23.4.0

![image](https://github.com/thebookisclosed/AmperageKit/assets/34286756/77da0fca-669f-4b25-8ab1-d7a54dc3ebd6)

**Comment by hazcod** [comment] 2024-06-06 07:03
Curious, what are the steps you took @Satertek ? I always get `Couldn't find AIX package`.
What insider channel are you on?
![image](https://github.com/thebookisclosed/AmperageKit/assets/5222512/aa9eae72-8da8-467c-b804-5fdcb18d2cce)

**Comment by MineraleYT** [comment] 2024-06-06 15:31
![Screenshot 2024-06-06 alle 17 33 09](https://github.com/thebookisclosed/AmperageKit/assets/66887063/ae8233aa-2d06-4565-86ce-870e68ee7e2e)

Same problem here!

**Comment by Satertek** [comment] 2024-06-06 16:04
I'm on the Dev channel.  It sounds like the Windows builds you both have are not yet supported.  If you're already in the Dev insider channel, due to the way Microsoft rolls out these builds there's probably nothing you can do other than download an ISO of a specific build and manually reinstall or wait for your system to be updated.

https://blogs.windows.com/windows-insider/2024/05/31/announcing-windows-11-insider-preview-build-26120-751-dev-channel/

**Comment by MineraleYT** [comment] 2024-06-06 16:09
Thanks for the response. 
I saw that there was an update on Windows Update and now it works. 
I can confirm that it works on Windows Build 10.0.26120.751 using Parallels on M2 Pro.
![Screenshot 2024-06-06 alle 18 09 16](https://github.com/thebookisclosed/AmperageKit/assets/66887063/dc3cf505-5725-4aa7-bb64-e2b6ae9965ad)

**Comment by hazcod** [comment] 2024-06-07 06:46
Can confirm, the latest dev release fixes it for me on M2 Parallels Win11.

**Comment by Rastafabisch** [comment] 2024-06-09 12:02
I can confirm as well, it's working fine. Currently running the latest build of Sonoma (14.5.1) and VMWare Fusion (13.5.2) as well as Windows 24H2 (26100.172) on a MacBook Pro 16" M1 Pro.

**Comment by grumpykiwi** [comment] 2024-06-09 13:24
Yes. I managed to get it working on my Mac yesterday after trying again from scratch. I had inadvertently clicked the wrong link on the page and got a different build. All works now. Thanks


Mark Nash

IT Director

(817) 465-9277  |  Arlington, Tx

Winner of 104 IABC Gold Quills and the 2023 Large Agency of the Year

[cid:linkedin_4c6f3bdf-dd4e-4f46-94f0-1885fa83094c.png]<https://www.linkedin.com/company/partnercomm>    [cid:instagram_bebedbe2-cb80-462a-af3c-7ae9caf0718c.png] <https://www.instagram.com/partnercomm>     [cid:facebook_a2d99c62-cb5a-42d3-b0e4-d08e71427149.png] <https://www.facebook.com/PartnerCommInc/>     [cid:twitter_53725725-ce5d-4ef3-bd47-bfd64fe511d7.png] <https://twitter.com/partnercomm>     [cid:vimeo_f71007e4-e318-469a-b82c-5751fc4fbe28.png] <https://vimeo.com/sweet250>                  [cid:web_a51bd891-a842-461a-b706-81937a9daae4.png]  www.partnercomm.net<https://www.partnercomm.net>
        [cid:logo-pcomm-30_74bce84a-c4e7-4724-87ee-9c2ca3e3421e.png]

________________________________

**Comment by hazcod** [comment] 2024-06-10 07:48
@grumpykiwi Let's close this issue I'd say.

**Comment by grumpykiwi** [comment] 2024-06-10 13:05
Yes. Works for me. Thx


Mark Nash

IT Director

(817) 465-9277  |  Arlington, Tx

Winner of 104 IABC Gold Quills and the 2023 Large Agency of the Year

[cid:linkedin_4c6f3bdf-dd4e-4f46-94f0-1885fa83094c.png]<https://www.linkedin.com/company/partnercomm>    [cid:instagram_bebedbe2-cb80-462a-af3c-7ae9caf0718c.png] <https://www.instagram.com/partnercomm>     [cid:facebook_a2d99c62-cb5a-42d3-b0e4-d08e71427149.png] <https://www.facebook.com/PartnerCommInc/>     [cid:twitter_53725725-ce5d-4ef3-bd47-bfd64fe511d7.png] <https://twitter.com/partnercomm>     [cid:vimeo_f71007e4-e318-469a-b82c-5751fc4fbe28.png] <https://vimeo.com/sweet250>                  [cid:web_a51bd891-a842-461a-b706-81937a9daae4.png]  www.partnercomm.net<https://www.partnercomm.net>
        [cid:logo-pcomm-30_74bce84a-c4e7-4724-87ee-9c2ca3e3421e.png]

________________________________

**Closed as completed** 2024-06-21 16:30 UTC
